<footer>
    <div class="copyright">
        <div class="container">
            <p><a class="copyright-link">
                    Учреждение образования «Гомельский государственный университет имени Франциска Скорины»&nbsp;1997-
                    <script type="text/javascript">
                        var d = new Date();
                        document.write(d.getFullYear() + " г.");
                    </script>
                </a></p>
        </div>
    </div>
</footer>
